# Generated by Django 4.2.20 on 2025-05-05 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0003_compra_estado_plantacion_estado_venta_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='tipoentrega',
            field=models.CharField(choices=[('S', 'Saco'), ('U', 'Unidad')], default=1, max_length=1, verbose_name='Tipo de entrega'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='venta',
            name='estado',
            field=models.BooleanField(default=False, verbose_name='Pagado'),
        ),
    ]
