# Generated by Django 4.2.20 on 2025-05-06 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0004_venta_tipoentrega_alter_venta_estado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plantacion',
            old_name='idfruto',
            new_name='cultivo',
        ),
    ]
