# Generated by Django 4.2.20 on 2025-05-08 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0007_alter_venta_tipoentrega'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantacion',
            name='estado',
            field=models.BooleanField(default=False, verbose_name='Finalizado'),
        ),
    ]
