# Generated by Django 4.2.20 on 2025-05-08 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0009_remove_venta_cantidad_venta_primera_venta_rechazo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cosecha',
            name='estado',
            field=models.BooleanField(default=False, verbose_name='Finalizado'),
        ),
    ]
