# Generated by Django 4.2.20 on 2025-05-08 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0011_remove_cosecha_rechazo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='rechazo',
        ),
    ]
