# Generated by Django 4.2.20 on 2025-05-11 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0013_parcela_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='cosecha',
            name='tipocosecha',
            field=models.CharField(choices=[('S', 'Saco'), ('U', 'Unidad'), ('MS', 'Medio saco'), ('C', 'Caja'), ('MC', 'Media caja')], default=1, max_length=2, verbose_name='Tipo de corte'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='parcela',
            name='estado',
            field=models.BooleanField(default=True, verbose_name='Ocupada'),
        ),
    ]
