# Generated by Django 4.2.20 on 2025-05-11 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0014_cosecha_tipocosecha_alter_parcela_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='tipoentrega',
        ),
    ]
