# Generated by Django 4.2.20 on 2025-05-19 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0016_alter_cosecha_tipocosecha_alter_parcela_estado_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cultivo',
            old_name='idfruto',
            new_name='idcultivo',
        ),
    ]
