# Generated by Django 4.2 on 2025-06-16 04:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0018_alter_parcela_estado_alter_plantacion_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compra',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='compra',
            name='precio',
        ),
        migrations.RemoveField(
            model_name='compra',
            name='producto',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='cosecha',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='primera',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='segunda',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='tercera',
        ),
        migrations.AddField(
            model_name='compra',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='compra',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestor.cliente', verbose_name='Proveedor'),
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primera', models.IntegerField(default=0)),
                ('segunda', models.IntegerField(default=0)),
                ('tercera', models.IntegerField(default=0)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cosecha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestor.cosecha')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestor.venta')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.CharField(max_length=300, verbose_name='Producto')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestor.compra')),
            ],
        ),
    ]
