# Generated by Django 4.2 on 2025-06-17 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0019_remove_compra_cantidad_remove_compra_precio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='tipomercado',
            field=models.CharField(choices=[('F', 'Formal'), ('I', 'Informal')], max_length=1, null=True, verbose_name='Tipo mercado'),
        ),
    ]
