# Generated by Django 4.2 on 2025-06-18 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0020_cliente_tipomercado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalleventa',
            name='cosecha',
        ),
        migrations.RemoveField(
            model_name='detalleventa',
            name='venta',
        ),
        migrations.DeleteModel(
            name='DetalleCompra',
        ),
        migrations.DeleteModel(
            name='DetalleVenta',
        ),
    ]
