# Generated by Django 4.2 on 2025-06-18 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0021_remove_detalleventa_cosecha_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primera', models.IntegerField(default=0)),
                ('segunda', models.IntegerField(default=0)),
                ('tercera', models.IntegerField(default=0)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cosecha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestor.cosecha')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestor.venta')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.CharField(max_length=300, verbose_name='Producto')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestor.compra')),
            ],
        ),
    ]
