# Generated by Django 4.2 on 2025-06-21 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0022_detalleventa_detallecompra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='total',
        ),
    ]
