# Generated by Django 4.2 on 2025-06-22 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0023_remove_venta_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalleventa',
            name='primera',
        ),
        migrations.RemoveField(
            model_name='detalleventa',
            name='segunda',
        ),
        migrations.RemoveField(
            model_name='detalleventa',
            name='tercera',
        ),
        migrations.RemoveField(
            model_name='detalleventa',
            name='total',
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='cantidad',
            field=models.PositiveIntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='categoria',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
