# Generated by Django 4.2 on 2025-06-24 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0024_remove_detalleventa_primera_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalleventa',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='detalleventa',
            name='categoria',
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='primera',
            field=models.IntegerField(default=0, verbose_name='Primera'),
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='segunda',
            field=models.IntegerField(default=0, verbose_name='Segunda'),
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='tercera',
            field=models.IntegerField(default=0, verbose_name='Tercera'),
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total'),
        ),
    ]
