# Generated by Django 4.2 on 2025-06-25 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0025_remove_detalleventa_cantidad_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalleventa',
            name='primera',
        ),
        migrations.RemoveField(
            model_name='detalleventa',
            name='segunda',
        ),
        migrations.RemoveField(
            model_name='detalleventa',
            name='tercera',
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='cantidad',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='categoria',
            field=models.CharField(choices=[('primera', 'Primera'), ('segunda', 'Segunda'), ('tercera', 'Tercera')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
