# Generated by Django 4.2 on 2025-06-28 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0027_remove_detalleventa_total_detalleventa_subtotal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cosecha',
            name='primera',
        ),
        migrations.RemoveField(
            model_name='cosecha',
            name='segunda',
        ),
        migrations.RemoveField(
            model_name='cosecha',
            name='tercera',
        ),
        migrations.RemoveField(
            model_name='cosecha',
            name='tipocosecha',
        ),
        migrations.CreateModel(
            name='DetalleCosecha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('primera', 'Primera'), ('segunda', 'Segunda'), ('tercera', 'Tercera')], max_length=10, verbose_name='Categoria')),
                ('tipocosecha', models.CharField(choices=[('S', 'Saco'), ('U', 'Unidad'), ('MS', 'Medio saco'), ('C', 'Caja'), ('MC', 'Media caja'), ('Lb', 'Libras')], max_length=2, verbose_name='Tipo de corte')),
                ('cantidad', models.IntegerField(verbose_name='Cantidad')),
                ('cosecha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestor.cosecha')),
            ],
        ),
    ]
