# Generated by Django 4.2 on 2025-08-07 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0028_remove_cosecha_primera_remove_cosecha_segunda_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('idempleado', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=300, verbose_name='Nombre')),
                ('telefono', models.CharField(max_length=300, verbose_name='Teléfono')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('salario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Salario')),
            ],
        ),
        migrations.RenameField(
            model_name='detallecompra',
            old_name='precio_unitario',
            new_name='preciounitario',
        ),
        migrations.CreateModel(
            name='Planilla',
            fields=[
                ('idplanilla', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(auto_now_add=True, verbose_name='Fecha de pago')),
                ('horastrabajas', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Horas extra')),
                ('horasextra', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Horas extra')),
                ('pagoextra', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Pago extra')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestor.empleado', verbose_name='Empleado')),
            ],
        ),
    ]
