# Generated by Django 4.2 on 2025-08-08 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0029_empleado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planilla',
            name='horastrabajas',
        ),
        migrations.RemoveField(
            model_name='planilla',
            name='total',
        ),
        migrations.AddField(
            model_name='planilla',
            name='jornada',
            field=models.BooleanField(default=False, verbose_name='Jornada'),
        ),
    ]
