# Generated by Django 4.2 on 2025-08-10 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0030_remove_planilla_horastrabajas_remove_planilla_total_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='planilla',
            options={'ordering': ['-fecha', 'empleado__nombre']},
        ),
        migrations.AddField(
            model_name='planilla',
            name='observaciones',
            field=models.TextField(blank=True, null=True, verbose_name='Observaciones'),
        ),
        migrations.AlterUniqueTogether(
            name='planilla',
            unique_together={('empleado', 'fecha')},
        ),
    ]
