# Generated by Django 4.2 on 2025-08-10 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0031_alter_planilla_options_planilla_observaciones_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallecompra',
            name='tipodetalle',
            field=models.CharField(choices=[('C', 'Casa'), ('E', 'Empresa')], default=1, max_length=1, verbose_name='Tipo detalle'),
            preserve_default=False,
        ),
    ]
