# Generated by Django 4.2 on 2025-08-13 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0032_detallecompra_tipodetalle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='estado',
            field=models.BooleanField(default=False, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='planilla',
            name='horasextra',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Horas extra'),
        ),
        migrations.AlterField(
            model_name='planilla',
            name='pagoextra',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Pago extra'),
        ),
    ]
