# Generated by Django 4.2 on 2025-08-15 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0033_alter_compra_estado_alter_planilla_horasextra_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleventa',
            name='tipocosecha',
            field=models.CharField(choices=[('S', 'Saco'), ('U', 'Unidad'), ('MS', 'Medio saco'), ('C', 'Caja'), ('MC', 'Media caja'), ('Lb', 'Libras')], default=1, max_length=2, verbose_name='Tipo de cosecha'),
            preserve_default=False,
        ),
    ]
