# Generated by Django 4.2 on 2025-08-16 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0034_detalleventa_tipocosecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='planilla',
            name='horastrabajadas',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Horas trabajadas'),
        ),
    ]
