# Generated by Django 4.2 on 2025-08-21 02:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0035_planilla_horastrabajadas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallecosecha',
            name='tipocosecha',
            field=models.CharField(choices=[('S', 'Saco'), ('U', 'Unidad'), ('C', 'Caja')], max_length=2, verbose_name='Tipo de corte'),
        ),
        migrations.AlterField(
            model_name='detalleventa',
            name='tipocosecha',
            field=models.CharField(choices=[('S', 'Saco'), ('U', 'Unidad'), ('C', 'Caja')], max_length=2, verbose_name='Tipo de cosecha'),
        ),
        migrations.CreateModel(
            name='DetalleCultivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('primera', 'Primera'), ('segunda', 'Segunda'), ('tercera', 'Tercera')], max_length=10, verbose_name='Categoria')),
                ('tipocosecha', models.CharField(choices=[('S', 'Saco'), ('U', 'Unidad'), ('C', 'Caja')], max_length=2, verbose_name='Tipo de corte')),
                ('cantidad', models.IntegerField(verbose_name='Cantidad de unidades')),
                ('cultivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestor.cultivo', verbose_name='Cultivo')),
            ],
        ),
    ]
