# Generated by Django 4.2 on 2025-08-21 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0036_alter_detallecosecha_tipocosecha_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cultivo',
            options={'verbose_name': 'Cultivo', 'verbose_name_plural': 'Cultivos'},
        ),
        migrations.AlterModelOptions(
            name='detallecultivo',
            options={'verbose_name': 'Detalle de Cultivo', 'verbose_name_plural': 'Detalles de Cultivo'},
        ),
        migrations.AlterUniqueTogether(
            name='detallecultivo',
            unique_together={('cultivo', 'categoria', 'tipocosecha')},
        ),
    ]
