# Generated by Django 4.2 on 2025-08-22 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0037_alter_cultivo_options_alter_detallecultivo_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallecosecha',
            name='tipocosecha',
            field=models.CharField(choices=[('S', 'Saco'), ('U', 'Unidad'), ('C', 'Caja'), ('Lb', 'Libra')], max_length=2, verbose_name='Tipo de corte'),
        ),
        migrations.AlterField(
            model_name='detallecultivo',
            name='cantidad',
            field=models.IntegerField(verbose_name='Unidades'),
        ),
        migrations.AlterField(
            model_name='detallecultivo',
            name='tipocosecha',
            field=models.CharField(choices=[('S', 'Saco'), ('C', 'Caja'), ('Lb', 'Libra')], max_length=2, verbose_name='Tipo de corte'),
        ),
        migrations.AlterField(
            model_name='detalleventa',
            name='tipocosecha',
            field=models.CharField(choices=[('S', 'Saco'), ('U', 'Unidad'), ('C', 'Caja'), ('Lb', 'Libra')], max_length=2, verbose_name='Tipo de cosecha'),
        ),
    ]
