# Generated by Django 4.2 on 2025-10-16 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0038_alter_detallecosecha_tipocosecha_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallecosecha',
            name='rechazo',
            field=models.IntegerField(blank=True, default=0, verbose_name='Cantidad'),
            preserve_default=False,
        ),
    ]
