# Generated by Django 4.2 on 2025-10-16 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0039_detallecosecha_rechazo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallecosecha',
            name='rechazo',
            field=models.IntegerField(blank=True, default=0, verbose_name='Cantidad'),
        ),
    ]
