# Generated by Django 4.2 on 2025-10-20 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0040_alter_detallecosecha_rechazo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallecosecha',
            name='rechazo',
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='rechazo',
            field=models.IntegerField(blank=True, default=0, verbose_name='Cantidad'),
        ),
    ]
