# Generated by Django 4.2 on 2025-10-21 01:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0041_remove_detallecosecha_rechazo_detalleventa_rechazo'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleVentaRechazo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('primera', 'Primera'), ('segunda', 'Segunda'), ('tercera', 'Tercera')], max_length=10, verbose_name='Categoría')),
                ('tipocosecha', models.CharField(choices=[('S', 'Saco'), ('U', 'Unidad'), ('C', 'Caja'), ('Lb', 'Libra')], max_length=2, verbose_name='Tipo cosecha')),
                ('cantidad', models.PositiveIntegerField(default=0)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('detalleventa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rechazos', to='gestor.detalleventa')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestor.venta')),
            ],
            options={
                'verbose_name': 'Rechazo de Detalle de Venta',
                'verbose_name_plural': 'Rechazos de Detalles de Venta',
                'ordering': ['-fecha'],
            },
        ),
    ]
