# Generated by Django 4.2 on 2025-10-21 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0042_detalleventarechazo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleventa',
            name='rechazo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
