# Generated by Django 4.2 on 2025-10-21 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0043_alter_detalleventa_rechazo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DetalleVentaRechazo',
        ),
    ]
