# Generated by Django 4.2.20 on 2025-04-26 00:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('idcliente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=300, verbose_name='Nombre')),
                ('telefono', models.CharField(max_length=300, verbose_name='Teléfono')),
                ('tipocliente', models.CharField(choices=[('C', 'Comprador'), ('P', 'Proveedor')], max_length=1, verbose_name='Tipo cliente')),
                ('tipocompra', models.CharField(choices=[('M', 'Menudeo'), ('U', 'Unidad'), ('S', 'Saco')], max_length=1, verbose_name='Tipo compra')),
            ],
        ),
        migrations.CreateModel(
            name='Cosecha',
            fields=[
                ('idcosecha', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(auto_now_add=True, verbose_name='Fecha de cosecha')),
                ('primera', models.IntegerField(verbose_name='Primera calidad')),
                ('segunda', models.IntegerField(verbose_name='Segunda calidad')),
                ('tercera', models.IntegerField(verbose_name='Tercera calidad')),
                ('rechazo', models.IntegerField(verbose_name='Rechazo')),
            ],
        ),
        migrations.CreateModel(
            name='Cultivo',
            fields=[
                ('idfruto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=300, verbose_name='Nombre')),
                ('variedad', models.CharField(max_length=300, verbose_name='Variedad')),
            ],
        ),
        migrations.CreateModel(
            name='Parcela',
            fields=[
                ('idparcela', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=300, verbose_name='Nombre')),
                ('tipoparcela', models.CharField(choices=[('A', 'Campo abierto'), ('M', 'Malla')], max_length=1, verbose_name='Tipo')),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('idventa', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(auto_now_add=True, verbose_name='Fecha de venta')),
                ('cantidad', models.IntegerField(verbose_name='Cantidad vendida')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestor.cliente', verbose_name='Cliente')),
                ('cosecha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestor.cosecha', verbose_name='Cosecha')),
            ],
        ),
        migrations.CreateModel(
            name='Plantacion',
            fields=[
                ('idplantacion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(auto_now_add=True, verbose_name='Fecha de plantación')),
                ('cantidad', models.IntegerField(verbose_name='Cantidad de plantas')),
                ('idfruto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestor.cultivo', verbose_name='Cultivo')),
                ('parcela', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestor.parcela', verbose_name='Parcela')),
            ],
        ),
        migrations.AddField(
            model_name='cosecha',
            name='plantacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestor.plantacion', verbose_name='Plantación'),
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('idcompra', models.AutoField(primary_key=True, serialize=False)),
                ('producto', models.CharField(max_length=300, verbose_name='Producto')),
                ('fecha', models.DateField(auto_now_add=True, verbose_name='Fecha de compra')),
                ('cantidad', models.IntegerField(verbose_name='Cantidad comprada')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestor.cliente', verbose_name='Cliente')),
                ('cosecha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestor.cosecha', verbose_name='Cosecha')),
            ],
        ),
    ]
