# Generated by Django 4.2.20 on 2025-05-07 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0005_rename_idfruto_plantacion_cultivo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='precio',
        ),
        migrations.AddField(
            model_name='venta',
            name='total',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Total'),
            preserve_default=False,
        ),
    ]
