# Generated by Django 4.2.20 on 2025-05-08 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0008_alter_plantacion_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='cantidad',
        ),
        migrations.AddField(
            model_name='venta',
            name='primera',
            field=models.IntegerField(default=0, verbose_name='Primera'),
        ),
        migrations.AddField(
            model_name='venta',
            name='rechazo',
            field=models.IntegerField(default=0, verbose_name='Rechazo'),
        ),
        migrations.AddField(
            model_name='venta',
            name='segunda',
            field=models.IntegerField(default=0, verbose_name='Segunda'),
        ),
        migrations.AddField(
            model_name='venta',
            name='tercera',
            field=models.IntegerField(default=0, verbose_name='Tercera'),
        ),
    ]
