# Generated by Django 4.2.20 on 2025-05-08 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0010_cosecha_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cosecha',
            name='rechazo',
        ),
    ]
