# Generated by Django 4.2.20 on 2025-05-19 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0015_remove_venta_tipoentrega'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cosecha',
            name='tipocosecha',
            field=models.CharField(choices=[('S', 'Saco'), ('U', 'Unidad'), ('MS', 'Medio saco'), ('C', 'Caja'), ('MC', 'Media caja'), ('Lb', 'Libras')], max_length=2, verbose_name='Tipo de corte'),
        ),
        migrations.AlterField(
            model_name='parcela',
            name='estado',
            field=models.BooleanField(default=True, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='plantacion',
            name='estado',
            field=models.BooleanField(default=True, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='plantacion',
            name='fecha',
            field=models.DateField(auto_now_add=True, verbose_name='Fecha de plantacion'),
        ),
    ]
